version: '3'
services:
  demo:
    image: 900349303695.dkr.ecr.us-east-2.amazonaws.com/demo:latest
    build:
      context: demo
      dockerfile: Dockerfile
  landing:
    image: 900349303695.dkr.ecr.us-east-2.amazonaws.com/landing:latest
    build:
      context: landing
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - landing
      - demo
    links:
      - landing
      - demo
