FROM node:17.1-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
COPY nginx/nginx.conf nginx.conf


FROM nginx:1.22.1-alpine as prod-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/build /etc/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]